<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0-ios;net10.0-maccatalyst</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationTitle>Native WKWebView Drag Drop</ApplicationTitle>
    <ApplicationId>com.companyname.dragdropnativewkwebview</ApplicationId>
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>
    <SupportedOSPlatformVersion>15.0</SupportedOSPlatformVersion>
  </PropertyGroup>

  <ItemGroup>
    <BundleResource Include="..\NativeMobileWebViewShared\index.html" LogicalName="index.html" />
  </ItemGroup>

</Project>
